import '../models/bus_info.dart';
import '../models/bus_route.dart';
import '../models/bus_stop.dart';
import '../models/alert_info.dart';

class BusDataService {
  // SAMPLE / TEST DATA — not from live Firestore.
  // Replace these constants with real Firestore data once seeded.
  static const stops = <BusStop>[
    BusStop(name: 'RTC Complex'),
    BusStop(name: 'Dwaraka Bus Station'),
    BusStop(name: 'Maddilapalem'),
    BusStop(name: 'MVP Colony'),
    BusStop(name: 'Rushikonda'),
    BusStop(name: 'Beach Road'),
    BusStop(name: 'Jagadamba Junction'),
    BusStop(name: 'Kailasagiri'),
    BusStop(name: 'HB Colony'),
    BusStop(name: 'Seethammadhara'),
    BusStop(name: 'Madhurawada'),
    BusStop(name: 'NAD Junction'),
    BusStop(name: 'Gopalapatnam'),
    BusStop(name: 'Simhachalam'),
    BusStop(name: 'Airport'),
    BusStop(name: 'Gajuwaka'),
    BusStop(name: 'Kurmannapalem'),
    BusStop(name: 'Steel Plant'),
    BusStop(name: 'Bheemunipatnam'),
    BusStop(name: 'Anandapuram'),
    BusStop(name: 'Kothavalasa'),
  ];

  static const routes = <BusRoute>[
    BusRoute(
      routeNumber: '540',
      title: 'Maddilapalem → Simhachalam',
      startingPoint: 'Maddilapalem',
      destination: 'Simhachalam',
      stops: [
        'Maddilapalem',
        'RTC Complex',
        'Dwaraka Bus Station',
        'HB Colony',
        'MVP Colony',
        'Seethammadhara',
        'NAD Junction',
        'Gopalapatnam',
        'Simhachalam',
      ],
      distance: '22 km',
      duration: '55 min',
      totalStops: 9,
      firstBus: '05:10 AM',
      lastBus: '10:45 PM',
      frequency: '15-20 min',
      description:
          'APSRTC route 540 connects central Visakhapatnam with Simhachalam temple via major city stops.',
    ),
    BusRoute(
      routeNumber: '541',
      title: 'Maddilapalem → Kothavalasa',
      startingPoint: 'Maddilapalem',
      destination: 'Kothavalasa',
      stops: [
        'Maddilapalem',
        'RTC Complex',
        'Dwaraka Bus Station',
        'HB Colony',
        'MVP Colony',
        'Seethammadhara',
        'NAD Junction',
        'Gopalapatnam',
        'Gajuwaka',
        'Anandapuram',
        'Kothavalasa',
      ],
      distance: '48 km',
      duration: '95 min',
      totalStops: 11,
      firstBus: '05:00 AM',
      lastBus: '09:30 PM',
      frequency: '20-25 min',
      description:
          'APSRTC route 541 runs from Maddilapalem to Kothavalasa via main Visakhapatnam hubs.',
    ),
    // NOTE: Routes below need verification against official APSRTC schedules.
    BusRoute(
      routeNumber: '12D',
      title: 'RTC Complex → Rushikonda',
      startingPoint: 'RTC Complex',
      destination: 'Rushikonda',
      stops: [
        'RTC Complex',
        'Jagadamba Junction',
        'Beach Road',
        'MVP Colony',
        'Rushikonda',
      ],
      distance: '18 km',
      duration: '40 min',
      totalStops: 5,
      firstBus: '06:00 AM',
      lastBus: '10:00 PM',
      frequency: '20-30 min',
      description: 'Route 12D — details pending verification.',
    ),
    BusRoute(
      routeNumber: '28K',
      title: 'Dwaraka Bus Station → Kailasagiri',
      startingPoint: 'Dwaraka Bus Station',
      destination: 'Kailasagiri',
      stops: [
        'Dwaraka Bus Station',
        'RTC Complex',
        'MVP Colony',
        'Kailasagiri',
      ],
      distance: '15 km',
      duration: '35 min',
      totalStops: 4,
      firstBus: '06:30 AM',
      lastBus: '09:30 PM',
      frequency: '30-40 min',
      description: 'Route 28K — details pending verification.',
    ),
    BusRoute(
      routeNumber: '48A',
      title: 'Maddilapalem → Gajuwaka',
      startingPoint: 'Maddilapalem',
      destination: 'Gajuwaka',
      stops: [
        'Maddilapalem',
        'RTC Complex',
        'NAD Junction',
        'Gopalapatnam',
        'Gajuwaka',
      ],
      distance: '20 km',
      duration: '50 min',
      totalStops: 5,
      firstBus: '05:30 AM',
      lastBus: '09:00 PM',
      frequency: '25-35 min',
      description: 'Route 48A — details pending verification.',
    ),
    BusRoute(
      routeNumber: '60C',
      title: 'Simhachalam → Beach Road',
      startingPoint: 'Simhachalam',
      destination: 'Beach Road',
      stops: [
        'Simhachalam',
        'Gopalapatnam',
        'NAD Junction',
        'MVP Colony',
        'Beach Road',
      ],
      distance: '24 km',
      duration: '60 min',
      totalStops: 5,
      firstBus: '05:00 AM',
      lastBus: '10:00 PM',
      frequency: '20-30 min',
      description: 'Route 60C — details pending verification.',
    ),
    BusRoute(
      routeNumber: '222V',
      title: 'RTC Complex → Steel Plant',
      startingPoint: 'RTC Complex',
      destination: 'Steel Plant',
      stops: [
        'RTC Complex',
        'Gajuwaka',
        'Kurmannapalem',
        'Steel Plant',
      ],
      distance: '30 km',
      duration: '70 min',
      totalStops: 4,
      firstBus: '05:15 AM',
      lastBus: '08:45 PM',
      frequency: '30-45 min',
      description: 'Route 222V — details pending verification.',
    ),
    BusRoute(
      routeNumber: '333',
      title: 'Maddilapalem → Bheemunipatnam',
      startingPoint: 'Maddilapalem',
      destination: 'Bheemunipatnam',
      stops: [
        'Maddilapalem',
        'RTC Complex',
        'Beach Road',
        'Rushikonda',
        'Bheemunipatnam',
      ],
      distance: '35 km',
      duration: '80 min',
      totalStops: 5,
      firstBus: '05:30 AM',
      lastBus: '09:00 PM',
      frequency: '40-60 min',
      description: 'Route 333 — details pending verification.',
    ),
    BusRoute(
      routeNumber: '368',
      title: 'Dwaraka Bus Station → Madhurawada',
      startingPoint: 'Dwaraka Bus Station',
      destination: 'Madhurawada',
      stops: [
        'Dwaraka Bus Station',
        'RTC Complex',
        'Seethammadhara',
        'MVP Colony',
        'Madhurawada',
      ],
      distance: '21 km',
      duration: '55 min',
      totalStops: 5,
      firstBus: '06:00 AM',
      lastBus: '10:00 PM',
      frequency: '25-35 min',
      description: 'Route 368 — details pending verification.',
    ),
    BusRoute(
      routeNumber: '600',
      title: 'RTC Complex → RTC Complex (Circular)',
      startingPoint: 'RTC Complex',
      destination: 'RTC Complex',
      stops: [
        'RTC Complex',
        'Jagadamba Junction',
        'Beach Road',
        'MVP Colony',
        'NAD Junction',
        'RTC Complex',
      ],
      distance: '26 km',
      duration: '75 min',
      totalStops: 6,
      firstBus: '05:00 AM',
      lastBus: '11:00 PM',
      frequency: '20-25 min',
      description: 'Route 600 circular service — details pending verification.',
    ),
    BusRoute(
      routeNumber: '69',
      title: 'Airport → Simhachalam',
      startingPoint: 'Airport',
      destination: 'Simhachalam',
      stops: [
        'Airport',
        'NAD Junction',
        'Gopalapatnam',
        'Simhachalam',
      ],
      distance: '19 km',
      duration: '45 min',
      totalStops: 4,
      firstBus: '06:00 AM',
      lastBus: '10:30 PM',
      frequency: '30-40 min',
      description: 'Route 69 — details pending verification.',
    ),
    BusRoute(
      routeNumber: '999',
      title: 'Maddilapalem → Vizag Steel Plant',
      startingPoint: 'Maddilapalem',
      destination: 'Steel Plant',
      stops: [
        'Maddilapalem',
        'RTC Complex',
        'Gajuwaka',
        'Kurmannapalem',
        'Steel Plant',
      ],
      distance: '38 km',
      duration: '90 min',
      totalStops: 5,
      firstBus: '05:00 AM',
      lastBus: '09:00 PM',
      frequency: '60-90 min',
      description: 'Route 999 — details pending verification.',
    ),
  ];

  static const buses = <BusInfo>[
    BusInfo(
      busNumber: '540',
      routeNumber: '540',
      routeName: 'Maddilapalem → Simhachalam',
      startingPoint: 'Maddilapalem',
      destination: 'Simhachalam',
      stops: [
        'Maddilapalem',
        'RTC Complex',
        'Dwaraka Bus Station',
        'HB Colony',
        'MVP Colony',
        'Seethammadhara',
        'NAD Junction',
        'Gopalapatnam',
        'Simhachalam',
      ],
      currentStop: 'HB Colony',
      nextStop: 'MVP Colony',
      eta: '5 min',
      status: BusStatus.onTime,
      busType: BusType.standard,
      driverName: 'Raghav',
      capacity: 52,
      availableSeats: 18,
      speed: 42.5,
      lastUpdated: '2 min ago',
      distanceRemaining: '13 km',
      estimatedJourneyTime: '32 min',
      isActive: true,
      latitude: 0.0,
      longitude: 0.0,
    ),
    BusInfo(
      busNumber: '541',
      routeNumber: '541',
      routeName: 'Maddilapalem → Kothavalasa',
      startingPoint: 'Maddilapalem',
      destination: 'Kothavalasa',
      stops: [
        'Maddilapalem',
        'RTC Complex',
        'Dwaraka Bus Station',
        'HB Colony',
        'MVP Colony',
        'Seethammadhara',
        'NAD Junction',
        'Gopalapatnam',
        'Gajuwaka',
        'Anandapuram',
        'Kothavalasa',
      ],
      currentStop: 'MVP Colony',
      nextStop: 'Seethammadhara',
      eta: '7 min',
      status: BusStatus.arrivingSoon,
      busType: BusType.express,
      driverName: 'Suresh',
      capacity: 52,
      availableSeats: 8,
      speed: 50.0,
      lastUpdated: '1 min ago',
      distanceRemaining: '28 km',
      estimatedJourneyTime: '55 min',
      isActive: true,
      latitude: 0.0,
      longitude: 0.0,
    ),
    BusInfo(
      busNumber: '12D',
      routeNumber: '12D',
      routeName: 'RTC Complex → Rushikonda',
      startingPoint: 'RTC Complex',
      destination: 'Rushikonda',
      stops: [
        'RTC Complex',
        'Jagadamba Junction',
        'Beach Road',
        'MVP Colony',
        'Rushikonda',
      ],
      currentStop: 'Jagadamba Junction',
      nextStop: 'Beach Road',
      eta: '8 min',
      status: BusStatus.onTime,
      busType: BusType.standard,
      driverName: 'Kiran',
      capacity: 40,
      availableSeats: 22,
      speed: 35.0,
      lastUpdated: '3 min ago',
      distanceRemaining: '9 km',
      estimatedJourneyTime: '22 min',
      isActive: true,
      latitude: 0.0,
      longitude: 0.0,
    ),
    BusInfo(
      busNumber: '28K',
      routeNumber: '28K',
      routeName: 'Dwaraka Bus Station → Kailasagiri',
      startingPoint: 'Dwaraka Bus Station',
      destination: 'Kailasagiri',
      stops: [
        'Dwaraka Bus Station',
        'RTC Complex',
        'MVP Colony',
        'Kailasagiri',
      ],
      currentStop: 'RTC Complex',
      nextStop: 'MVP Colony',
      eta: '12 min',
      status: BusStatus.delayed,
      busType: BusType.standard,
      driverName: 'Ravi',
      capacity: 40,
      availableSeats: 15,
      speed: 28.0,
      lastUpdated: '5 min ago',
      distanceRemaining: '8 km',
      estimatedJourneyTime: '25 min',
      isActive: true,
      latitude: 0.0,
      longitude: 0.0,
    ),
    BusInfo(
      busNumber: '48A',
      routeNumber: '48A',
      routeName: 'Maddilapalem → Gajuwaka',
      startingPoint: 'Maddilapalem',
      destination: 'Gajuwaka',
      stops: [
        'Maddilapalem',
        'RTC Complex',
        'NAD Junction',
        'Gopalapatnam',
        'Gajuwaka',
      ],
      currentStop: 'NAD Junction',
      nextStop: 'Gopalapatnam',
      eta: '10 min',
      status: BusStatus.onTime,
      busType: BusType.standard,
      driverName: 'Mohan',
      capacity: 50,
      availableSeats: 30,
      speed: 40.0,
      lastUpdated: '4 min ago',
      distanceRemaining: '12 km',
      estimatedJourneyTime: '35 min',
      isActive: true,
      latitude: 0.0,
      longitude: 0.0,
    ),
    BusInfo(
      busNumber: '60C',
      routeNumber: '60C',
      routeName: 'Simhachalam → Beach Road',
      startingPoint: 'Simhachalam',
      destination: 'Beach Road',
      stops: [
        'Simhachalam',
        'Gopalapatnam',
        'NAD Junction',
        'MVP Colony',
        'Beach Road',
      ],
      currentStop: 'NAD Junction',
      nextStop: 'MVP Colony',
      eta: '6 min',
      status: BusStatus.arrivingSoon,
      busType: BusType.ac,
      driverName: 'Sekhar',
      capacity: 45,
      availableSeats: 12,
      speed: 45.0,
      lastUpdated: '2 min ago',
      distanceRemaining: '14 km',
      estimatedJourneyTime: '40 min',
      isActive: true,
      latitude: 0.0,
      longitude: 0.0,
    ),
    BusInfo(
      busNumber: '222V',
      routeNumber: '222V',
      routeName: 'RTC Complex → Steel Plant',
      startingPoint: 'RTC Complex',
      destination: 'Steel Plant',
      stops: [
        'RTC Complex',
        'Gajuwaka',
        'Kurmannapalem',
        'Steel Plant',
      ],
      currentStop: 'Gajuwaka',
      nextStop: 'Kurmannapalem',
      eta: '15 min',
      status: BusStatus.onTime,
      busType: BusType.express,
      driverName: 'Prasad',
      capacity: 52,
      availableSeats: 35,
      speed: 55.0,
      lastUpdated: '6 min ago',
      distanceRemaining: '18 km',
      estimatedJourneyTime: '50 min',
      isActive: true,
      latitude: 0.0,
      longitude: 0.0,
    ),
    BusInfo(
      busNumber: '333',
      routeNumber: '333',
      routeName: 'Maddilapalem → Bheemunipatnam',
      startingPoint: 'Maddilapalem',
      destination: 'Bheemunipatnam',
      stops: [
        'Maddilapalem',
        'RTC Complex',
        'Beach Road',
        'Rushikonda',
        'Bheemunipatnam',
      ],
      currentStop: 'Beach Road',
      nextStop: 'Rushikonda',
      eta: '20 min',
      status: BusStatus.diverted,
      busType: BusType.standard,
      driverName: 'Venkat',
      capacity: 40,
      availableSeats: 25,
      speed: 38.0,
      lastUpdated: '7 min ago',
      distanceRemaining: '22 km',
      estimatedJourneyTime: '65 min',
      isActive: true,
      latitude: 0.0,
      longitude: 0.0,
    ),
    BusInfo(
      busNumber: '368',
      routeNumber: '368',
      routeName: 'Dwaraka Bus Station → Madhurawada',
      startingPoint: 'Dwaraka Bus Station',
      destination: 'Madhurawada',
      stops: [
        'Dwaraka Bus Station',
        'RTC Complex',
        'Seethammadhara',
        'MVP Colony',
        'Madhurawada',
      ],
      currentStop: 'Seethammadhara',
      nextStop: 'MVP Colony',
      eta: '9 min',
      status: BusStatus.onTime,
      busType: BusType.standard,
      driverName: 'Naidu',
      capacity: 45,
      availableSeats: 20,
      speed: 42.0,
      lastUpdated: '3 min ago',
      distanceRemaining: '11 km',
      estimatedJourneyTime: '38 min',
      isActive: true,
      latitude: 0.0,
      longitude: 0.0,
    ),
    BusInfo(
      busNumber: '600',
      routeNumber: '600',
      routeName: 'RTC Complex → RTC Complex (Circular)',
      startingPoint: 'RTC Complex',
      destination: 'RTC Complex',
      stops: [
        'RTC Complex',
        'Jagadamba Junction',
        'Beach Road',
        'MVP Colony',
        'NAD Junction',
        'RTC Complex',
      ],
      currentStop: 'Beach Road',
      nextStop: 'MVP Colony',
      eta: '4 min',
      status: BusStatus.arrivingSoon,
      busType: BusType.ac,
      driverName: 'Raju',
      capacity: 50,
      availableSeats: 10,
      speed: 48.0,
      lastUpdated: '1 min ago',
      distanceRemaining: '16 km',
      estimatedJourneyTime: '45 min',
      isActive: true,
      latitude: 0.0,
      longitude: 0.0,
    ),
    BusInfo(
      busNumber: '69',
      routeNumber: '69',
      routeName: 'Airport → Simhachalam',
      startingPoint: 'Airport',
      destination: 'Simhachalam',
      stops: [
        'Airport',
        'NAD Junction',
        'Gopalapatnam',
        'Simhachalam',
      ],
      currentStop: 'NAD Junction',
      nextStop: 'Gopalapatnam',
      eta: '11 min',
      status: BusStatus.onTime,
      busType: BusType.express,
      driverName: 'Babu',
      capacity: 48,
      availableSeats: 28,
      speed: 52.0,
      lastUpdated: '4 min ago',
      distanceRemaining: '10 km',
      estimatedJourneyTime: '30 min',
      isActive: true,
      latitude: 0.0,
      longitude: 0.0,
    ),
    BusInfo(
      busNumber: '999',
      routeNumber: '999',
      routeName: 'Maddilapalem → Vizag Steel Plant',
      startingPoint: 'Maddilapalem',
      destination: 'Steel Plant',
      stops: [
        'Maddilapalem',
        'RTC Complex',
        'Gajuwaka',
        'Kurmannapalem',
        'Steel Plant',
      ],
      currentStop: 'Gajuwaka',
      nextStop: 'Kurmannapalem',
      eta: '18 min',
      status: BusStatus.delayed,
      busType: BusType.express,
      driverName: 'Murali',
      capacity: 55,
      availableSeats: 40,
      speed: 45.0,
      lastUpdated: '8 min ago',
      distanceRemaining: '20 km',
      estimatedJourneyTime: '60 min',
      isActive: true,
      latitude: 0.0,
      longitude: 0.0,
    ),
  ];

  static const alerts = <AlertInfo>[
    AlertInfo(
      title: 'Bus 540B delayed',
      message:
          'Heavy traffic on the HB Colony stretch is slowing down the service.',
      type: AlertType.delay,
      timestamp: 'Just now',
    ),
    AlertInfo(
      title: 'Route 541 diverted',
      message: 'Route 541 will bypass Gopalapatnam for the next 30 minutes.',
      type: AlertType.diverted,
      timestamp: '5 min ago',
    ),
    AlertInfo(
      title: 'Bus 541X arriving soon',
      message: 'Bus 541X reaches MVP Colony in 7 minutes.',
      type: AlertType.arrivingSoon,
      timestamp: '2 min ago',
    ),
    AlertInfo(
      title: 'Service cancelled',
      message: 'One 540 service has been cancelled due to driver availability.',
      type: AlertType.cancelled,
      timestamp: '10 min ago',
    ),
    AlertInfo(
      title: 'Heavy traffic',
      message: 'Rushikonda road is congested. Expect longer travel times.',
      type: AlertType.traffic,
      timestamp: '15 min ago',
    ),
  ];
}
